package tiers

// tierMap holds the mapping of source names to tier levels (1-4).
// Tier 1 = most authoritative, Tier 4 = least.
var tierMap = map[string]int{
	// ── Tier 1: Major wire services, papers of record, global broadsheets ──
	"reuters":           1,
	"ap":                1,
	"afp":               1,
	"bbc":               1,
	"bbc-world":         1,
	"bbc-news":          1,
	"nyt":               1,
	"nyt-world":         1,
	"washpost":          1,
	"washpost-world":    1,
	"guardian":          1,
	"guardian-world":    1,
	"ft":                1,
	"economist":         1,
	"wsj":               1,
	"bloomberg":         1,
	"bloomberg-econ":    1,
	"bloomberg-markets": 1,
	"xinhua":            1,
	"tass":              1,
	"kyodo":             1,
	"efe":               1,
	"ansa":              1,
	"dpa":               1,
	"pti":               1,
	"yonhap":            1,

	// ── Tier 2: Major national/regional outlets ──────────────────────────
	"cnn":            2,
	"aljazeera":      2,
	"dw":             2,
	"dw-world":       2,
	"france24":       2,
	"scmp":           2,
	"nikkei":         2,
	"nikkei-asia":    2,
	"times":          2,
	"telegraph":      2,
	"politico":       2,
	"axios":          2,
	"npr":            2,
	"npr-world":      2,
	"abc-au":         2,
	"cbc":            2,
	"rte":            2,
	"ard":            2,
	"zdf":            2,
	"lemonde":        2,
	"elpais":         2,
	"corriere":       2,
	"asahi":          2,
	"mainichi":       2,
	"hankyoreh":      2,
	"joongang":       2,
	"straitstimes":   2,
	"bangkokpost":    2,
	"hindustan":      2,
	"dawn":           2,
	"dailystar-bd":   2,
	"nation-ke":      2,
	"dailymaverick":  2,
	"globo":          2,
	"clarin":         2,
	"reforma":        2,
	"haaretz":        2,
	"timesofisrael":  2,
	"arabnews":       2,
	"thenational-ae": 2,
	"japantimes":     2,
	"chinadaily":     2,
	"globaltimes":    2,
	"rt":             2,
	"cnbc":           2,
	"marketwatch":    2,
	"abc-us":         2,
	"cbsnews":        2,
	"nbcnews":        2,
	"foxnews":        2,
	"sky":            2,
	"independent":    2,
	"mirror":         2,

	// ── Tier 3: Specialised / digital-first / think tanks ───────────────
	"techcrunch":        3,
	"arstechnica":       3,
	"wired":             3,
	"theverge":          3,
	"mit-tech-review":   3,
	"hackernews":        3,
	"defenseone":        3,
	"thehill":           3,
	"foreignpolicy":     3,
	"foreignaffairs":    3,
	"brookings":         3,
	"cfr":               3,
	"chathamhouse":      3,
	"csis":              3,
	"rand":              3,
	"iiss":              3,
	"carnegie":          3,
	"sipri":             3,
	"icg":               3,
	"worldbank":         3,
	"imf":               3,
	"who":               3,
	"reliefweb":         3,
	"gdacs":             3,
	"usgs-quakes":       3,
	"acleddata":         3,
	"vox":               3,
	"theintercept":      3,
	"propublica":        3,
	"motherjones":       3,
	"theatlantic":       3,
	"newyorker":         3,
	"spectator":         3,
	"thediplomatmag":    3,
	"restofworld":       3,
	"devex":             3,
	"irdrinternational": 3,
	"euronews":          3,
	"dwnews":            3,
	"trtworld":          3,
	"i24news":           3,

	// ── Tier 4: Aggregators, lesser-known, niche, social ────────────────
	"newsapi":      4,
	"googlenews":   4,
	"bingNews":     4,
	"feedly":       4,
	"flipboard":    4,
	"reddit":       4,
	"twitter":      4,
	"telegram":     4,
	"substack":     4,
	"medium":       4,
	"zerohedge":    4,
	"oann":         4,
	"breitbart":    4,
	"dailywire":    4,
	"commondreams": 4,
	"jacobin":      4,
	"counterpunch": 4,
	"mintpress":    4,
	"grayzone":     4,
	"globalvoices": 4,
}

// GetTier returns the tier (1-4) for a source name. Unknown sources default to 4.
func GetTier(sourceName string) int {
	if t, ok := tierMap[sourceName]; ok {
		return t
	}
	return 4
}

// AllTiers returns a copy of the full tier mapping.
func AllTiers() map[string]int {
	out := make(map[string]int, len(tierMap))
	for k, v := range tierMap {
		out[k] = v
	}
	return out
}
