import type { SemanticFeedItem, InsightsResult, TopicSuggestion, EventAnalysis } from "./types";

// ── Mock digest items (simulating semantic layer output) ─────────────────

export const MOCK_DIGEST: SemanticFeedItem[] = [
  {
    title: "AI 监管新政：欧盟发布最新人工智能法案实施细则",
    link: "https://reuters.com/ai-regulation-2026",
    description: "欧盟委员会今日发布了 AI 法案的详细实施指南，涵盖高风险 AI 系统的合规要求、透明度义务和处罚标准。该法案将于 2026 年底全面生效。",
    pubDate: "2026-04-28T06:30:00Z",
    source: "Reuters",
    hash: "a1b2c3d4e5f60001",
    severity: 5,
    categories: ["technology", "regulation"],
    importanceScore: 0.92,
    stage: "DEVELOPING",
    corroboration: 8,
    tier: 1,
  },
  {
    title: "美联储会议纪要释放鸽派信号，市场反应积极",
    link: "https://bloomberg.com/fed-minutes-2026",
    description: "最新公布的联邦公开市场委员会会议纪要显示，多数委员倾向于在未来几个月内开始降息周期。美股三大指数应声上涨。",
    pubDate: "2026-04-28T05:45:00Z",
    source: "Bloomberg",
    hash: "a1b2c3d4e5f60002",
    severity: 4,
    categories: ["finance", "macro"],
    importanceScore: 0.87,
    stage: "BREAKING",
    corroboration: 12,
    tier: 1,
  },
  {
    title: "中东局势：红海航运危机持续升级",
    link: "https://aljazeera.com/red-sea-crisis",
    description: "胡塞武装持续攻击红海商船，多家航运公司绕道好望角，全球供应链成本显著上升。美军和英军对胡塞据点实施新一轮打击。",
    pubDate: "2026-04-28T04:20:00Z",
    source: "Al Jazeera",
    hash: "a1b2c3d4e5f60003",
    severity: 6,
    categories: ["conflict", "geopolitics", "energy"],
    importanceScore: 0.95,
    stage: "SUSTAINED",
    corroboration: 15,
    tier: 1,
  },
  {
    title: "半导体出口管制升级：日荷最新限制措施分析",
    link: "https://techcrunch.com/semiconductor-export-controls",
    description: "日本和荷兰政府相继发布新的半导体设备出口管制措施，进一步限制先进制程技术出口。中国半导体产业面临更大压力。",
    pubDate: "2026-04-28T03:50:00Z",
    source: "TechCrunch",
    hash: "a1b2c3d4e5f60004",
    severity: 5,
    categories: ["geopolitics", "technology"],
    importanceScore: 0.88,
    stage: "DEVELOPING",
    corroboration: 9,
    tier: 2,
  },
  {
    title: "全球碳排放达到新高，COP 会议各方博弈加剧",
    link: "https://nature.com/carbon-emissions-record",
    description: "最新研究数据显示全球碳排放量再创历史新高，各国在即将召开的 COP 大会上立场分歧明显加大。发展中国家要求发达国家加大减排力度。",
    pubDate: "2026-04-28T02:10:00Z",
    source: "Nature",
    hash: "a1b2c3d4e5f60005",
    severity: 3,
    categories: ["climate", "environment"],
    importanceScore: 0.72,
    stage: "SUSTAINED",
    corroboration: 6,
    tier: 1,
  },
  {
    title: "量子计算突破：Google 实现百万量子比特纠错",
    link: "https://arxiv.org/quantum-error-correction",
    description: "Google Quantum AI 团队在最新论文中展示了百万量子比特级别的纠错能力，推动量子优越性实现。业界认为这是量子计算商用化的关键一步。",
    pubDate: "2026-04-28T01:30:00Z",
    source: "arXiv",
    hash: "a1b2c3d4e5f60006",
    severity: 3,
    categories: ["technology", "research"],
    importanceScore: 0.68,
    stage: "BREAKING",
    corroboration: 4,
    tier: 2,
  },
  {
    title: "OpenAI 推出新一代推理模型 o3-mini",
    link: "https://theverge.com/openai-o3-mini",
    description: "OpenAI 发布 o3-mini 推理模型，在数学和编程任务上表现大幅提升，同时推理成本降低 60%。模型已面向所有 ChatGPT Plus 用户开放。",
    pubDate: "2026-04-27T22:00:00Z",
    source: "The Verge",
    hash: "a1b2c3d4e5f60007",
    severity: 4,
    categories: ["technology", "ai"],
    importanceScore: 0.82,
    stage: "DEVELOPING",
    corroboration: 11,
    tier: 2,
  },
  {
    title: "全球粮食安全预警：厄尔尼诺影响评估报告",
    link: "https://worldbank.org/el-nino-food-security",
    description: "世界银行发布最新报告，评估厄尔尼诺气候现象对全球粮食供应链的潜在影响和政策建议。预计影响将持续至 2027 年初。",
    pubDate: "2026-04-27T20:00:00Z",
    source: "World Bank",
    hash: "a1b2c3d4e5f60008",
    severity: 2,
    categories: ["economy", "agriculture"],
    importanceScore: 0.55,
    stage: "SUSTAINED",
    corroboration: 3,
    tier: 1,
  },
  {
    title: "SpaceX 星舰第六次试飞成功回收助推器",
    link: "https://spacenews.com/starship-flight-6",
    description: "SpaceX 完成星舰第六次试飞，成功实现助推器空中回收，标志着全面可重复使用火箭的重要里程碑。马斯克称今年将实现轨道飞行。",
    pubDate: "2026-04-27T18:30:00Z",
    source: "SpaceNews",
    hash: "a1b2c3d4e5f60009",
    severity: 2,
    categories: ["technology", "aerospace"],
    importanceScore: 0.58,
    stage: "FADING",
    corroboration: 7,
    tier: 2,
  },
  {
    title: "新型固态电池技术突破量产瓶颈",
    link: "https://technologyreview.com/solid-state-battery",
    description: "日本丰田与中国宁德时代分别宣布固态电池技术突破，预计 2026 年实现量产。能量密度提升 50%，充电速度提升 3 倍。",
    pubDate: "2026-04-27T16:00:00Z",
    source: "MIT Tech Review",
    hash: "a1b2c3d4e5f60010",
    severity: 3,
    categories: ["technology", "energy"],
    importanceScore: 0.65,
    stage: "DEVELOPING",
    corroboration: 5,
    tier: 2,
  },
  {
    title: "全球央行数字货币进展追踪",
    link: "https://bis.org/cbdc-tracker",
    description: "国际清算银行最新报告显示全球超过 90% 的央行正在研究 CBDC，其中 11 个已正式启动试点。中国数字人民币交易额突破 10 万亿元。",
    pubDate: "2026-04-27T14:00:00Z",
    source: "BIS",
    hash: "a1b2c3d4e5f60011",
    severity: 1,
    categories: ["finance", "digital-currency"],
    importanceScore: 0.42,
    stage: "SUSTAINED",
    corroboration: 2,
    tier: 1,
  },
  {
    title: "DeepMind AlphaFold3 解析蛋白质-药物互作",
    link: "https://science.org/alphafold3",
    description: "DeepMind 发布 AlphaFold3 升级版，能够精确预测蛋白质与小分子药物的结合模式，加速药物研发。已有多家药企接入合作。",
    pubDate: "2026-04-27T12:00:00Z",
    source: "Science",
    hash: "a1b2c3d4e5f60012",
    severity: 2,
    categories: ["health", "ai", "research"],
    importanceScore: 0.52,
    stage: "FADING",
    corroboration: 3,
    tier: 1,
  },
  {
    title: "台海局势紧张：解放军在台湾海峡举行大规模军演",
    link: "https://scmp.com/taiwan-strait-drills",
    description: "中国人民解放军在台湾海峡及周边海域举行联合军事演习，出动航母编队和多型先进战机。美国国防部对此表示密切关注。",
    pubDate: "2026-04-27T10:00:00Z",
    source: "SCMP",
    hash: "a1b2c3d4e5f60013",
    severity: 7,
    categories: ["conflict", "military", "geopolitics"],
    importanceScore: 0.98,
    stage: "BREAKING",
    corroboration: 18,
    tier: 2,
  },
  {
    title: "欧洲能源转型加速：德国提前关闭最后一批煤电厂",
    link: "https://ft.com/germany-coal-phaseout",
    description: "德国宣布将在 2027 年前关闭最后一批煤电厂，比原计划提前 3 年。可再生能源占比已超过 65%。",
    pubDate: "2026-04-27T08:00:00Z",
    source: "Financial Times",
    hash: "a1b2c3d4e5f60014",
    severity: 2,
    categories: ["energy", "environment", "europe"],
    importanceScore: 0.60,
    stage: "DEVELOPING",
    corroboration: 4,
    tier: 1,
  },
  {
    title: "印度成为全球第三大经济体，GDP 超越日本",
    link: "https://economist.com/india-gdp-japan",
    description: "根据 IMF 最新数据，按美元计价印度 GDP 正式超过日本，成为全球第三大经济体。莫迪政府称将在 2030 年前达到 5 万亿美元。",
    pubDate: "2026-04-27T06:00:00Z",
    source: "The Economist",
    hash: "a1b2c3d4e5f60015",
    severity: 3,
    categories: ["economy", "geopolitics"],
    importanceScore: 0.75,
    stage: "DEVELOPING",
    corroboration: 10,
    tier: 1,
  },
];

// ── Mock insights (simulating InsightsSource output) ─────────────────────

export const MOCK_INSIGHTS: InsightsResult = {
  summary:
    "过去 24 小时全球情报监控摘要：台海军事演习引发地缘政治紧张升级，成为最高优先级事件（18 源佐证）；" +
    "红海航运危机持续影响全球供应链（15 源佐证）；欧盟 AI 法案实施细则发布，科技监管趋严；" +
    "美联储鸽派信号推动全球市场乐观情绪；半导体出口管制进一步升级。" +
    "技术领域方面，量子计算和固态电池均有重大突破，OpenAI 发布新模型 o3-mini。" +
    "整体情感偏中性略负面，地缘政治和军事冲突类事件主导本期重要度排名。",
  headlines: [
    "台海局势紧张：解放军在台湾海峡举行大规模军演",
    "中东局势：红海航运危机持续升级",
    "AI 监管新政：欧盟发布最新人工智能法案实施细则",
    "美联储会议纪要释放鸽派信号，市场反应积极",
    "半导体出口管制升级：日荷最新限制措施分析",
    "OpenAI 推出新一代推理模型 o3-mini",
    "印度成为全球第三大经济体，GDP 超越日本",
    "全球碳排放达到新高，COP 会议各方博弈加剧",
    "量子计算突破：Google 实现百万量子比特纠错",
    "新型固态电池技术突破量产瓶颈",
  ],
  generatedAt: "2026-04-28T07:00:00Z",
};

// ── Mock topic suggestions (derived from semantic analysis) ──────────────

export const MOCK_TOPIC_SUGGESTIONS: TopicSuggestion[] = [
  {
    title: "台海军演与全球供应链风险联动分析",
    reason: "最高 severity(7) BREAKING 事件 + 18 源佐证，台海局势与半导体供应链高度关联",
    score: 96,
    categories: ["conflict", "geopolitics", "technology"],
    relatedCount: 23,
  },
  {
    title: "欧盟 AI 法案对中国科技企业的影响分析",
    reason: "热度上升 +42%，多源佐证充分，跨 regulation + technology 类别",
    score: 92,
    categories: ["technology", "regulation"],
    relatedCount: 15,
  },
  {
    title: "半导体管制升级下的国产替代进展",
    reason: "DEVELOPING 事件 + 9 源佐证，跨地缘政治和科技类别",
    score: 88,
    categories: ["geopolitics", "technology"],
    relatedCount: 12,
  },
  {
    title: "红海危机对全球能源与航运成本的深度影响",
    reason: "SUSTAINED 持续事件，severity 6，15 源佐证，影响多个产业链",
    score: 85,
    categories: ["conflict", "energy", "geopolitics"],
    relatedCount: 18,
  },
  {
    title: "全球央行货币政策转向信号与市场机遇",
    reason: "美联储鸽派信号 BREAKING + 12 源佐证，金融市场关注度高",
    score: 79,
    categories: ["finance", "macro"],
    relatedCount: 14,
  },
];

// ── Category label mapping ───────────────────────────────────────────────

export const CATEGORY_LABELS: Record<string, string> = {
  conflict: "冲突",
  military: "军事",
  geopolitics: "地缘政治",
  technology: "科技",
  regulation: "监管",
  finance: "金融",
  macro: "宏观",
  climate: "气候",
  environment: "环境",
  energy: "能源",
  economy: "经济",
  agriculture: "农业",
  health: "医疗",
  ai: "AI",
  research: "研究",
  aerospace: "航天",
  "digital-currency": "数字货币",
  europe: "欧洲",
};

export function getCategoryLabel(cat: string): string {
  return CATEGORY_LABELS[cat] ?? cat;
}

// ── Mock per-item event analyses ────────────────────────────────────────

export const MOCK_EVENT_ANALYSES: Record<string, EventAnalysis> = {
  // 台海局势 (hash: a1b2c3d4e5f60013)
  a1b2c3d4e5f60013: {
    entities: [
      { text: "中国人民解放军", type: "ORG", confidence: 0.98 },
      { text: "台湾海峡", type: "LOC", confidence: 0.97 },
      { text: "美国国防部", type: "ORG", confidence: 0.95 },
      { text: "台湾", type: "LOC", confidence: 0.96 },
      { text: "习近平", type: "PER", confidence: 0.82 },
    ],
    sentiment: { label: "negative", score: 0.89 },
    impact: {
      scope: "global",
      sectors: ["半导体", "航运", "金融市场", "国防"],
      disruption: 0.92,
      summary: "台海军事演习显著升级地缘紧张态势，全球半导体供应链面临中断风险，亚太航运保险费率上涨，金融市场避险情绪升温。",
    },
    timeline: [
      { date: "2026-04-25", label: "解放军宣布在台海周边进行联合军事演习" },
      { date: "2026-04-26", label: "航母编队进入演习区域，多型战机出动" },
      { date: "2026-04-27", label: "美国国防部声明密切关注局势" },
      { date: "2026-04-28", label: "演习规模扩大，实弹射击科目进行中" },
    ],
    actions: [
      "监控台积电等关键半导体企业的生产和出货情况",
      "关注亚太区域航运保险费率变动",
      "跟踪美日澳等国的外交和军事回应",
      "评估受影响企业的供应链替代方案",
    ],
    generatedAt: "2026-04-28T07:15:00Z",
  },

  // 红海航运危机 (hash: a1b2c3d4e5f60003)
  a1b2c3d4e5f60003: {
    entities: [
      { text: "胡塞武装", type: "ORG", confidence: 0.97 },
      { text: "红海", type: "LOC", confidence: 0.99 },
      { text: "好望角", type: "LOC", confidence: 0.95 },
      { text: "美军", type: "ORG", confidence: 0.93 },
      { text: "英军", type: "ORG", confidence: 0.91 },
      { text: "马士基", type: "ORG", confidence: 0.85 },
    ],
    sentiment: { label: "negative", score: 0.84 },
    impact: {
      scope: "global",
      sectors: ["航运", "能源", "零售", "制造业"],
      disruption: 0.78,
      summary: "红海航运中断导致全球约15%的海运贸易受影响，集装箱运费上涨200%以上，欧亚贸易通道受阻，能源和消费品供应链成本大幅上升。",
    },
    timeline: [
      { date: "2025-11-19", label: "胡塞武装开始攻击红海商船" },
      { date: "2025-12-18", label: "美国宣布组建护航联盟" },
      { date: "2026-01-12", label: "美英对胡塞据点实施打击" },
      { date: "2026-03-15", label: "多家航运公司宣布长期绕道好望角" },
      { date: "2026-04-28", label: "新一轮打击后，攻击频率暂时下降" },
    ],
    actions: [
      "评估供应链对苏伊士运河路线的依赖程度",
      "关注国际原油和天然气价格波动",
      "监控集装箱运费指数（SCFI/FBX）走势",
      "跟踪联合国及地区调解进展",
    ],
    generatedAt: "2026-04-28T07:10:00Z",
  },

  // 欧盟AI法案 (hash: a1b2c3d4e5f60001)
  a1b2c3d4e5f60001: {
    entities: [
      { text: "欧盟委员会", type: "ORG", confidence: 0.98 },
      { text: "欧盟", type: "ORG", confidence: 0.99 },
      { text: "Thierry Breton", type: "PER", confidence: 0.78 },
    ],
    sentiment: { label: "neutral", score: 0.62 },
    impact: {
      scope: "global",
      sectors: ["科技", "AI", "金融科技", "医疗科技", "自动驾驶"],
      disruption: 0.55,
      summary: "欧盟AI法案将深刻影响全球AI产业格局。高风险AI系统合规成本预计增加15-30%，中国和美国科技企业进入欧盟市场的门槛显著提高。",
    },
    timeline: [
      { date: "2024-03-13", label: "欧洲议会投票通过AI法案" },
      { date: "2024-08-01", label: "法案正式生效" },
      { date: "2025-08-02", label: "禁止性AI实践条款开始执行" },
      { date: "2026-04-28", label: "发布详细实施指南和合规框架" },
      { date: "2026-12-31", label: "全面合规截止日期" },
    ],
    actions: [
      "审查企业AI产品是否属于高风险分类",
      "启动合规差距分析和整改计划",
      "关注同行企业的合规策略和成本估算",
      "评估数据治理流程是否满足透明度要求",
    ],
    generatedAt: "2026-04-28T07:05:00Z",
  },

  // 美联储鸽派信号 (hash: a1b2c3d4e5f60002)
  a1b2c3d4e5f60002: {
    entities: [
      { text: "联邦公开市场委员会", type: "ORG", confidence: 0.97 },
      { text: "美联储", type: "ORG", confidence: 0.99 },
      { text: "Jerome Powell", type: "PER", confidence: 0.88 },
    ],
    sentiment: { label: "positive", score: 0.76 },
    impact: {
      scope: "global",
      sectors: ["金融", "房地产", "科技", "新兴市场"],
      disruption: 0.35,
      summary: "美联储鸽派信号预示降息周期启动，全球风险资产受益。新兴市场资本流入预期改善，科技股估值逻辑获得支撑，房地产市场有望企稳回升。",
    },
    timeline: [
      { date: "2026-03-20", label: "FOMC维持利率不变，声明措辞温和" },
      { date: "2026-04-15", label: "通胀数据回落至3.2%" },
      { date: "2026-04-28", label: "会议纪要显示多数委员支持降息" },
    ],
    actions: [
      "关注6月FOMC会议利率决议",
      "评估固定收益和权益类资产配置比例",
      "监控美元指数和新兴市场货币走势",
      "跟踪房地产和科技板块资金流向",
    ],
    generatedAt: "2026-04-28T07:08:00Z",
  },
};
